language: ruby
rvm:
- ruby-head
deploy:
  provider: heroku
  app: nameless-inlet-75977
  api_key:
    secure: py32Ywj9oO+UrsG/H/AmgGxCzUKiRdSK0FacR/4t6iFmxh8JRZMlhQJnutjTX0lBhI+TstHUhXR4ukOp8mBI6ExGdDM5vI3X/XrK1r0WETEKOfnVDZ8oSA6s6CGPXDYIosbFCNF1o1/dINvlfHM5NBcRM772Dif6ZOGv/54idi63b+uyVqlBE0YU4vDJ8a5d3xuVFpfa9dlPnT7my4aixdifnYp2irp4gvci5dnR3ViI58nFD7DbSwEjt6o7w6VC+CdLyMunqzd0mZ/v4hQmDwtdahgZeV8BxAo+jSaRkjelRNFpl5hEBz4LvnfwDe7cIczK2Enx1tfzsLN26sy/zQmSZKIZRRXHTnkuEHOvbWb1St1T42xb9sfR5fYAYnUPUDYSk939F+MvxZQVmFIMVjoeaf/HDI583NyFYVn1Xtetbji4xa6fbfLRhS/INM9/P0hcx8COujAEwrx20y5PJ8H9Wz28yPhB1DP9rtInRYlTCN7XewXpKKyL63KYSDTdHBGVstzH6qMKZlKrkam5Z7mwLY2clTsuv75fdQxXJuiUUN0wWAT8/g86mMWeZw2y8YcSW8FJglUXbOSQdGyO5D4zf7BgORI6Bx/eoRwUidtp6cxwdU+/lbZRpO5WneealdIDUpHD+aZgSAIAUJY+obAMaOl7Cs8tvS6Ip0xGSpc=
